### ISSUE TITLE
`Aux` is a reserved word on Windows

### ISSUE THREAD

**Issue by marchchad** [docusign/eg-02-react-implicit-grant#2]
I cannot successfully clone or download and unpack the repository on a Windows machine because of the directory `/src/hoc/Aux`.

It doesn't look like much of a component to recreate under a different directory name, but still a hassle to have to rewrite code to get it to work.

**Comment by marchchad** [comment]
Rather than renaming it, since its purpose seems to be wrapping multiple child components in order to meet React's requirement of returning a single node, please consider using React's built-in [Fragment](https://reactjs.org/docs/fragments.html#short-syntax) instead.

This will help to remove any obscurities and make it clear what code in this example is related to DocuSign workflows and what is React code.

**Comment by LarryKlugerDS** [comment]
Thank you for the excellent suggestion.

This is an old example and React has moved on quite a bit since then. The example needs to be re-written.
